$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1428321654079.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"21a11ac89fea4574803208da37407b4b",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b7bf42b231c4a129dcf08e6b78005da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673cbc01c7e048fe8d35ed964858d36d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"75bfd33d593e41629ec93ab5cea8ddff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec4777c2fd8c49ecb1f55d97a179d177",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.jpg"}},
{
          "id":"8d7605fb1d144112bd9e4e10b42ae810",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":60},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推荐",
                      "target":{
                        "targetType":"page",
                        "url":"推荐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4d6c6014f4da41c0a8f2041ef3cbee5b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":60},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 曲库",
                      "target":{
                        "targetType":"page",
                        "url":"曲库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eeba7290f52d41b6859c623a6b3be085",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":60},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e3f6ed7a63ce4c60815b2271226e873a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":190},
            "size":{
              "width":480,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 本地歌曲",
                      "target":{
                        "targetType":"page",
                        "url":"本地歌曲.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9d97a1e452e3450985e5a16132886e2c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1050},
            "size":{
              "width":470,
              "height":96}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 歌唱页",
                      "target":{
                        "targetType":"page",
                        "url":"歌唱页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0052a7cd023b4069b4855cd57deadc5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":144,
              "y":791},
            "size":{
              "width":363,
              "height":159},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2609336e8a314401818a0faeddc30bc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":144,
                  "y":791},
                "size":{
                  "width":363,
                  "height":159},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u9.png"}},
{
          "id":"59880220bd2f40fd9cd0cf2abb1ab56d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":226,
              "y":840},
            "size":{
              "width":214,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 (文本框(单行)) = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["59880220bd2f40fd9cd0cf2abb1ab56d"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"a8db1e3ff5134b5ead1615347ee0d95a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":144,
              "y":791},
            "size":{
              "width":363,
              "height":39},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e882fa01ff401581d7955afcd3d166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":144,
                  "y":791},
                "size":{
                  "width":363,
                  "height":39},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"6f7bd005b2074f5998f8e763e543a3b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":144,
              "y":890},
            "size":{
              "width":100,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94078725459145379e56edb520d22c2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":144,
                  "y":890},
                "size":{
                  "width":100,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"ed331d7859424145be064e4ce3826d4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":407,
              "y":890},
            "size":{
              "width":100,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62a18fd0cbac482596f8a1d4fb0c21c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":407,
                  "y":890},
                "size":{
                  "width":100,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u16.png"}},
{
          "id":"67a25c26238645d2a7cc95eff8e91e49",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":980},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (形状),<br>(文本框(单行)),<br>(Image),<br>(Image),<br>(Image)",
                      "objectsToFades":[{
                          "objectPath":["0052a7cd023b4069b4855cd57deadc5b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["59880220bd2f40fd9cd0cf2abb1ab56d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a8db1e3ff5134b5ead1615347ee0d95a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7bd005b2074f5998f8e763e543a3b6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ed331d7859424145be064e4ce3826d4b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"77569486053c4c739aa72737ea475604",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":890},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"557417524fde47b99dc31e7c528dd233",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":885},
            "size":{
              "width":58,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"97b35651707547be9c0e6df0d5fbdd1c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":980},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 (文本框(单行)),<br>(Image),<br>(Image),<br>(Image),<br>(图像热区),<br>(图像热区),<br>(形状)",
                      "objectsToFades":[{
                          "objectPath":["59880220bd2f40fd9cd0cf2abb1ab56d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a8db1e3ff5134b5ead1615347ee0d95a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6f7bd005b2074f5998f8e763e543a3b6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ed331d7859424145be064e4ce3826d4b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["67a25c26238645d2a7cc95eff8e91e49"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["77569486053c4c739aa72737ea475604"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0052a7cd023b4069b4855cd57deadc5b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "5b7bf42b231c4a129dcf08e6b78005da":{
      "scriptId":"u0"},
    "673cbc01c7e048fe8d35ed964858d36d":{
      "scriptId":"u1"},
    "75bfd33d593e41629ec93ab5cea8ddff":{
      "scriptId":"u2"},
    "ec4777c2fd8c49ecb1f55d97a179d177":{
      "scriptId":"u3"},
    "8d7605fb1d144112bd9e4e10b42ae810":{
      "scriptId":"u4"},
    "4d6c6014f4da41c0a8f2041ef3cbee5b":{
      "scriptId":"u5"},
    "eeba7290f52d41b6859c623a6b3be085":{
      "scriptId":"u6"},
    "e3f6ed7a63ce4c60815b2271226e873a":{
      "scriptId":"u7"},
    "9d97a1e452e3450985e5a16132886e2c":{
      "scriptId":"u8"},
    "0052a7cd023b4069b4855cd57deadc5b":{
      "scriptId":"u9"},
    "2609336e8a314401818a0faeddc30bc7":{
      "scriptId":"u10"},
    "59880220bd2f40fd9cd0cf2abb1ab56d":{
      "scriptId":"u11"},
    "a8db1e3ff5134b5ead1615347ee0d95a":{
      "scriptId":"u12"},
    "a9e882fa01ff401581d7955afcd3d166":{
      "scriptId":"u13"},
    "6f7bd005b2074f5998f8e763e543a3b6":{
      "scriptId":"u14"},
    "94078725459145379e56edb520d22c2f":{
      "scriptId":"u15"},
    "ed331d7859424145be064e4ce3826d4b":{
      "scriptId":"u16"},
    "62a18fd0cbac482596f8a1d4fb0c21c5":{
      "scriptId":"u17"},
    "67a25c26238645d2a7cc95eff8e91e49":{
      "scriptId":"u18"},
    "77569486053c4c739aa72737ea475604":{
      "scriptId":"u19"},
    "557417524fde47b99dc31e7c528dd233":{
      "scriptId":"u20"},
    "97b35651707547be9c0e6df0d5fbdd1c":{
      "scriptId":"u21"}}});