$axure.loadCurrentPage({
  "url":"歌唱页.html",
  "generationDate":new Date(1428321654349.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c6c7162a8e4940c980e87ead19b803b7",
    "type":"Axure:Page",
    "name":"歌唱页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0e70cbc8fcc44f75af3ce447bda81243",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a14043fb263848d9a4c766cda3ca71ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"dd218da4cac74932b60bf6f0e04eef5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68bcd8a510014cb1aca5d35c353e06b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"fea1f823fd8e433881392937fd7d4504",
          "label":"pm",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"56b5864ef7054039968aa5955f1dc962",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a5f9d4a5bf4a430ca708b6f4cafb7132",
                  "label":"",
                  "parentDynamicPanel":"fea1f823fd8e433881392937fd7d4504",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":1136}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4dfc75f8935540a4932f6b093bda557d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fea1f823fd8e433881392937fd7d4504",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":1136}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/歌唱页/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"81198d7ede9f45d5a4d21cb7ac44422a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":1074},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 wl hd 到 (0,0) 线性 120000ms",
                      "objectsToMoves":[{
                          "objectPath":["003d18a9615344af920d7333827a5a84"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":120000}}}]},
{
                      "action":"moveWidget",
                      "description":"移动 lyric hd 到 (0,-200) 线性 120000ms",
                      "objectsToMoves":[{
                          "objectPath":["a17147e27662469fbbf8fa3abf63997d"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-200",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":120000}}}]}]}]}},
          "tabbable":true},
{
          "id":"d7b73223ac4d473686510a13db259de2",
          "label":"wl",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1048},
            "size":{
              "width":640,
              "height":2}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2e70060be075470d9f5effbd4c2e6dc6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"003d18a9615344af920d7333827a5a84",
                  "label":"wl hd",
                  "parentDynamicPanel":"d7b73223ac4d473686510a13db259de2",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-650,
                      "y":0},
                    "size":{
                      "width":640,
                      "height":2}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"2af324b95cc841249666826985ea3a63",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"eb673b14bf1e4526b6a5acf8c5bb00cf",
                          "label":"",
                          "parentDynamicPanel":"003d18a9615344af920d7333827a5a84",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":640,
                              "height":2},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"123d70c48a384ad4b5b97fe01bf14c07",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"003d18a9615344af920d7333827a5a84",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":640,
                                  "height":2},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/歌唱页/u10.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"7374f89788d142de9c9e71c634825a6a",
          "label":"lyric",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":230},
            "size":{
              "width":390,
              "height":818}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a1a17e5b4a8241349cc6084f2aa95712",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a17147e27662469fbbf8fa3abf63997d",
                  "label":"lyric hd",
                  "parentDynamicPanel":"7374f89788d142de9c9e71c634825a6a",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":817},
                    "size":{
                      "width":390,
                      "height":1684}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"9ab8a5d0f41540a1b2bec43988b542c0",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"84502575b437437a94710a9ae3c57a2c",
                          "label":"",
                          "parentDynamicPanel":"a17147e27662469fbbf8fa3abf63997d",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"24px",
                            "horizontalAlignment":"center",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "location":{
                              "x":-10,
                              "y":0},
                            "size":{
                              "width":400,
                              "height":880}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f83368a2cf8e4bdc862ae67b3ccb4b50",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"a17147e27662469fbbf8fa3abf63997d",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"24px",
                                "horizontalAlignment":"center",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "location":{
                                  "x":-10,
                                  "y":0},
                                "size":{
                                  "width":400,
                                  "height":880}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"4c1d7f7460334c28a0379525a6e856f9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":90},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0e70cbc8fcc44f75af3ce447bda81243":{
      "scriptId":"u0"},
    "a14043fb263848d9a4c766cda3ca71ab":{
      "scriptId":"u1"},
    "dd218da4cac74932b60bf6f0e04eef5f":{
      "scriptId":"u2"},
    "68bcd8a510014cb1aca5d35c353e06b5":{
      "scriptId":"u3"},
    "fea1f823fd8e433881392937fd7d4504":{
      "scriptId":"u4"},
    "a5f9d4a5bf4a430ca708b6f4cafb7132":{
      "scriptId":"u5"},
    "4dfc75f8935540a4932f6b093bda557d":{
      "scriptId":"u6"},
    "81198d7ede9f45d5a4d21cb7ac44422a":{
      "scriptId":"u7"},
    "d7b73223ac4d473686510a13db259de2":{
      "scriptId":"u8"},
    "003d18a9615344af920d7333827a5a84":{
      "scriptId":"u9"},
    "eb673b14bf1e4526b6a5acf8c5bb00cf":{
      "scriptId":"u10"},
    "123d70c48a384ad4b5b97fe01bf14c07":{
      "scriptId":"u11"},
    "7374f89788d142de9c9e71c634825a6a":{
      "scriptId":"u12"},
    "a17147e27662469fbbf8fa3abf63997d":{
      "scriptId":"u13"},
    "84502575b437437a94710a9ae3c57a2c":{
      "scriptId":"u14"},
    "f83368a2cf8e4bdc862ae67b3ccb4b50":{
      "scriptId":"u15"},
    "4c1d7f7460334c28a0379525a6e856f9":{
      "scriptId":"u16"}}});