$axure.loadCurrentPage({
  "url":"推荐.html",
  "generationDate":new Date(1428321654464.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5bfce2427f7f4bb6a0ab36474250014d",
    "type":"Axure:Page",
    "name":"推荐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5f114dd886e9438cb59745e0a1ef8e49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eea80641aae4627a0b072c881e4856f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"7426640c66ae441594d07a87e50c731c",
          "label":"banner",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":138},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 banner 到 Next 向左滑动 out 500ms 向左滑动 in 500ms 自动循环 循环间隔 1000 毫秒,<br>dot 到 Next 自动循环 循环间隔 1000 毫秒",
                      "panelsToStates":[{
                          "panelPath":["7426640c66ae441594d07a87e50c731c"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":1000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}},
{
                          "panelPath":["18e3321487f04b2487a0f7284a21a05a"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":1000,
                            "options":{
                              "compress":false}}}]}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 banner 到 Previous 向右滑动 out 500ms 向右滑动 in 500ms 自动循环 循环间隔 1000 毫秒,<br>dot 到 Previous 自动循环 循环间隔 1000 毫秒",
                      "panelsToStates":[{
                          "panelPath":["7426640c66ae441594d07a87e50c731c"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":1000,
                            "options":{
                              "animateOut":{
                                "easing":"slideRight",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}},
{
                          "panelPath":["18e3321487f04b2487a0f7284a21a05a"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":1000,
                            "options":{
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f0a47ee705c34ec8b1e2907f12d96505",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ee5648153cb64d928bb11fbe1c42b6bc",
                  "label":"",
                  "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4146e444a5184ae28d8e7b9f7e4abc9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"7383e7e03cad4db1971c4b26317f4cf3",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"92c94cfc46ee4ae98bc562ea893a6373",
                  "label":"",
                  "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a662968ba20441ae94972b289bf24892",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2c76d12ddbd54bd89a2cd9ced045919f",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d3ce70834866448795457dd2bd532a2e",
                  "label":"",
                  "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67745eb49a784193abdb2cddb9da2392",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u7.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"74a8af67c7794505941f1acd60423241",
              "label":"状态4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f3eedd7e97d14ebbb534e97c95aecbbd",
                  "label":"",
                  "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"025519650a4b4943bcc77510569bc00d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u9.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ef2ae969e5b04b92a44061b0a1f2861d",
              "label":"状态5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fbeacc19ebc64b7f8de7ba9baefd1cbd",
                  "label":"",
                  "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8b36dca0b3b4d55aa7294f3b55febb4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u11.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"86e0ae018dab480f8ade57ad6dcea97c",
              "label":"状态6",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cd156fa80ced458bb7d0a4c44b68b951",
                  "label":"",
                  "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30fb5bd0d3d840ba98f9a9f9e12756fa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7426640c66ae441594d07a87e50c731c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u13.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"18e3321487f04b2487a0f7284a21a05a",
          "label":"dot",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":269,
              "y":385},
            "size":{
              "width":121,
              "height":12}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"19f10fac9e7947ae911d3ba0e626cce7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dcda61c6b46846259aa5ea95855361c9",
                  "label":"",
                  "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b673af91f12b44999eaa2ebea555d7d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":10}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u16.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0a65378627f84c7b841e0eaec066d087",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7f1b04e7b1f446d7a99db8d4f5819c7a",
                  "label":"",
                  "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dae6d3f3e1c0470fa5ca84ad5be6bf8a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":10}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u18.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ed88b6f013a74cd7a7399ad912979971",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6974fb82bb3c4f2daa0ba8e674f96683",
                  "label":"",
                  "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"280edd346ac94e4abfaa6bb0078d9d92",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":10}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u20.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"d7378aa04a5f45f190818fc0cc1b73a1",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d62bc19bb5d941db941a510ce4c234e1",
                  "label":"",
                  "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c222552b259d4a1dab198dc0b808b004",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":10}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u22.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"c1672cb611b94cbebfe00663c179f154",
              "label":"状态4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2c23ff8cab804366939482ce0b80fd78",
                  "label":"",
                  "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b33a75e4c2a4062a8f4198278f9600f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":10}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u24.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"add482e183994dbeb37c494cd4d5a7ef",
              "label":"状态5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"985a5b656b22410da0885ec297ff6eae",
                  "label":"",
                  "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":120,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"524b8a2b86ff4106868af29c49dd8e28",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"18e3321487f04b2487a0f7284a21a05a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":120,
                          "height":10}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐/u26.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"12d1a88482e6402f982806d3250f5e5a",
          "label":"pm",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":458},
            "size":{
              "width":640,
              "height":690}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1<br> (If area of pm hd 接触到 area of top 和 area of pm hd 接触到 area of low)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"IsOver",
                      "arguments":[{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["19e4321f491c47c1a0f57bec60cbd585"]}]},
{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["93a6c2e3719d4a1aa84d3aa84d505676"]}]}]},
                    "rightExpr":{
                      "exprType":"fcall",
                      "functionName":"IsOver",
                      "arguments":[{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["19e4321f491c47c1a0f57bec60cbd585"]}]},
{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["b8025922203c44b5ab9a315080d9a097"]}]}]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 沿 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["19e4321f491c47c1a0f57bec60cbd585"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"用例 2<br> (Else If area of pm hd 未接触 area of top)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["19e4321f491c47c1a0f57bec60cbd585"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["93a6c2e3719d4a1aa84d3aa84d505676"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 到 (0,0) 弹跳 500ms",
                      "objectsToMoves":[{
                          "objectPath":["19e4321f491c47c1a0f57bec60cbd585"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"easeOutBounce",
                              "duration":500}}}]}]},
{
                  "description":"用例 3<br> (Else If area of pm hd 未接触 area of low)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["19e4321f491c47c1a0f57bec60cbd585"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["b8025922203c44b5ab9a315080d9a097"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 到 (0,-860) 弹跳 500ms",
                      "objectsToMoves":[{
                          "objectPath":["19e4321f491c47c1a0f57bec60cbd585"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-860",
                              "stos":[]},
                            "options":{
                              "easing":"easeOutBounce",
                              "duration":500}}}]}]}]},
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 曲库",
                      "target":{
                        "targetType":"page",
                        "url":"曲库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"02fa1362f38c4d479aa4284c9498584b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"19e4321f491c47c1a0f57bec60cbd585",
                  "label":"pm hd",
                  "parentDynamicPanel":"12d1a88482e6402f982806d3250f5e5a",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":1550}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"d5dc75cab5844a689e9edf6e3106c40e",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"248ab88d3f1249da8534c2e9a48202ee",
                          "label":"",
                          "parentDynamicPanel":"19e4321f491c47c1a0f57bec60cbd585",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":640,
                              "height":1552}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0e50fd1aa7254d28bc630b2a4cad3c11",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"19e4321f491c47c1a0f57bec60cbd585",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":640,
                                  "height":1552}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/推荐/u30.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"93a6c2e3719d4a1aa84d3aa84d505676",
                  "label":"top",
                  "parentDynamicPanel":"12d1a88482e6402f982806d3250f5e5a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":240,
                      "y":0},
                    "size":{
                      "width":180,
                      "height":1}},
                  "adaptiveStyles":{
}},
{
                  "id":"b8025922203c44b5ab9a315080d9a097",
                  "label":"low",
                  "parentDynamicPanel":"12d1a88482e6402f982806d3250f5e5a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":689},
                    "size":{
                      "width":160,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"82a007a6c1c64bea9178e2ac83d08f02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e766cca296439299156eaff448567c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推荐/u34.png"}},
{
          "id":"7151e96e5a0f40dd9dfd43f87e9c2f28",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":70},
            "size":{
              "width":120,
              "height":58}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1171f49f0642422ebaad31a886585481",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":60},
            "size":{
              "width":100,
              "height":68}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 曲库",
                      "target":{
                        "targetType":"page",
                        "url":"曲库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"21605d8591ed43b3b6b01884dc777aae",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":60},
            "size":{
              "width":110,
              "height":68}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"934a2048f0a84ce2baaa8497d423364d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":480},
            "size":{
              "width":70,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 本地歌曲",
                      "target":{
                        "targetType":"page",
                        "url":"本地歌曲.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"48204e6ec99f4e59992e438d8670f4ce",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":480},
            "size":{
              "width":65,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 排行榜",
                      "target":{
                        "targetType":"page",
                        "url":"排行榜.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "5f114dd886e9438cb59745e0a1ef8e49":{
      "scriptId":"u0"},
    "1eea80641aae4627a0b072c881e4856f":{
      "scriptId":"u1"},
    "7426640c66ae441594d07a87e50c731c":{
      "scriptId":"u2"},
    "ee5648153cb64d928bb11fbe1c42b6bc":{
      "scriptId":"u3"},
    "4146e444a5184ae28d8e7b9f7e4abc9c":{
      "scriptId":"u4"},
    "92c94cfc46ee4ae98bc562ea893a6373":{
      "scriptId":"u5"},
    "a662968ba20441ae94972b289bf24892":{
      "scriptId":"u6"},
    "d3ce70834866448795457dd2bd532a2e":{
      "scriptId":"u7"},
    "67745eb49a784193abdb2cddb9da2392":{
      "scriptId":"u8"},
    "f3eedd7e97d14ebbb534e97c95aecbbd":{
      "scriptId":"u9"},
    "025519650a4b4943bcc77510569bc00d":{
      "scriptId":"u10"},
    "fbeacc19ebc64b7f8de7ba9baefd1cbd":{
      "scriptId":"u11"},
    "a8b36dca0b3b4d55aa7294f3b55febb4":{
      "scriptId":"u12"},
    "cd156fa80ced458bb7d0a4c44b68b951":{
      "scriptId":"u13"},
    "30fb5bd0d3d840ba98f9a9f9e12756fa":{
      "scriptId":"u14"},
    "18e3321487f04b2487a0f7284a21a05a":{
      "scriptId":"u15"},
    "dcda61c6b46846259aa5ea95855361c9":{
      "scriptId":"u16"},
    "b673af91f12b44999eaa2ebea555d7d1":{
      "scriptId":"u17"},
    "7f1b04e7b1f446d7a99db8d4f5819c7a":{
      "scriptId":"u18"},
    "dae6d3f3e1c0470fa5ca84ad5be6bf8a":{
      "scriptId":"u19"},
    "6974fb82bb3c4f2daa0ba8e674f96683":{
      "scriptId":"u20"},
    "280edd346ac94e4abfaa6bb0078d9d92":{
      "scriptId":"u21"},
    "d62bc19bb5d941db941a510ce4c234e1":{
      "scriptId":"u22"},
    "c222552b259d4a1dab198dc0b808b004":{
      "scriptId":"u23"},
    "2c23ff8cab804366939482ce0b80fd78":{
      "scriptId":"u24"},
    "8b33a75e4c2a4062a8f4198278f9600f":{
      "scriptId":"u25"},
    "985a5b656b22410da0885ec297ff6eae":{
      "scriptId":"u26"},
    "524b8a2b86ff4106868af29c49dd8e28":{
      "scriptId":"u27"},
    "12d1a88482e6402f982806d3250f5e5a":{
      "scriptId":"u28"},
    "19e4321f491c47c1a0f57bec60cbd585":{
      "scriptId":"u29"},
    "248ab88d3f1249da8534c2e9a48202ee":{
      "scriptId":"u30"},
    "0e50fd1aa7254d28bc630b2a4cad3c11":{
      "scriptId":"u31"},
    "93a6c2e3719d4a1aa84d3aa84d505676":{
      "scriptId":"u32"},
    "b8025922203c44b5ab9a315080d9a097":{
      "scriptId":"u33"},
    "82a007a6c1c64bea9178e2ac83d08f02":{
      "scriptId":"u34"},
    "28e766cca296439299156eaff448567c":{
      "scriptId":"u35"},
    "7151e96e5a0f40dd9dfd43f87e9c2f28":{
      "scriptId":"u36"},
    "1171f49f0642422ebaad31a886585481":{
      "scriptId":"u37"},
    "21605d8591ed43b3b6b01884dc777aae":{
      "scriptId":"u38"},
    "934a2048f0a84ce2baaa8497d423364d":{
      "scriptId":"u39"},
    "48204e6ec99f4e59992e438d8670f4ce":{
      "scriptId":"u40"}}});