$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1427553320192.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ff82d91d425146c1a99a1133d3ed0b28",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aa52acfbbddc4500a15a6a121df4fd02",
          "label":"pm",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6a11a396622a4e189d2fba673d7c080a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d358f8064cad4d03bfb300c7cfddbfb4",
                  "label":"pm hd",
                  "parentDynamicPanel":"aa52acfbbddc4500a15a6a121df4fd02",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"3c2fe5b86f3d43408ea6769c5fd1db7e",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"354527cc45db4bfaae42c0242edcbd4c",
                          "label":"",
                          "parentDynamicPanel":"d358f8064cad4d03bfb300c7cfddbfb4",
                          "type":"flowShape",
                          "styleType":"flowShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":640,
                              "height":1136}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3823569948d54065977ec58c704240f7",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d358f8064cad4d03bfb300c7cfddbfb4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":640,
                                  "height":1136}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/regen/u2.png"}},
{
                          "id":"62c5e19ad12241748e75e5b57d0bc8ea",
                          "label":"",
                          "parentDynamicPanel":"d358f8064cad4d03bfb300c7cfddbfb4",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":-350,
                              "y":240},
                            "size":{
                              "width":1280,
                              "height":800},
                            "rotation":"90",
                            "textRotation":"90"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c2e2815d06234fde9c59b4a37ac80925",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d358f8064cad4d03bfb300c7cfddbfb4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":-350,
                                  "y":240},
                                "size":{
                                  "width":1280,
                                  "height":800},
                                "rotation":"90",
                                "textRotation":"90"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/regen/u4.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"3cd844184b5945a68809c2b20a63348c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a07007240fe4a5486153d2009d34509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/regen/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aa52acfbbddc4500a15a6a121df4fd02":{
      "scriptId":"u0"},
    "d358f8064cad4d03bfb300c7cfddbfb4":{
      "scriptId":"u1"},
    "354527cc45db4bfaae42c0242edcbd4c":{
      "scriptId":"u2"},
    "3823569948d54065977ec58c704240f7":{
      "scriptId":"u3"},
    "62c5e19ad12241748e75e5b57d0bc8ea":{
      "scriptId":"u4"},
    "c2e2815d06234fde9c59b4a37ac80925":{
      "scriptId":"u5"},
    "3cd844184b5945a68809c2b20a63348c":{
      "scriptId":"u6"},
    "0a07007240fe4a5486153d2009d34509":{
      "scriptId":"u7"}}});