$axure.loadCurrentPage({
  "url":"批量操作.html",
  "generationDate":new Date(1428321654271.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1a2c1ea483a94f47a53795d30621a851",
    "type":"Axure:Page",
    "name":"批量操作",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"01bb3472ce954039b8dd5692fe77aea5",
          "label":"pm",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":70},
            "size":{
              "width":640,
              "height":1076}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1<br> (If area of pm hd 接触到 area of low 和 area of pm hd 接触到 area of tpo)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"IsOver",
                      "arguments":[{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["61f502c91582407f98946a8bcad5278c"]}]},
{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["67e5e818a18646ed985596cac13b50b0"]}]}]},
                    "rightExpr":{
                      "exprType":"fcall",
                      "functionName":"IsOver",
                      "arguments":[{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["61f502c91582407f98946a8bcad5278c"]}]},
{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["300406c57d6a4c9daff9f7c3cf90ed0e"]}]}]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 沿 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["61f502c91582407f98946a8bcad5278c"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"用例 2<br> (Else If area of pm hd 未接触 area of tpo)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["61f502c91582407f98946a8bcad5278c"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["300406c57d6a4c9daff9f7c3cf90ed0e"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 到 (0,0) 弹跳 500ms",
                      "objectsToMoves":[{
                          "objectPath":["61f502c91582407f98946a8bcad5278c"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"easeOutBounce",
                              "duration":500}}}]}]},
{
                  "description":"用例 3<br> (Else If area of pm hd 未接触 area of low)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["61f502c91582407f98946a8bcad5278c"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["67e5e818a18646ed985596cac13b50b0"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 到 (0,-863) 弹跳 500ms",
                      "objectsToMoves":[{
                          "objectPath":["61f502c91582407f98946a8bcad5278c"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-863",
                              "stos":[]},
                            "options":{
                              "easing":"easeOutBounce",
                              "duration":500}}}]}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推荐",
                      "target":{
                        "targetType":"page",
                        "url":"推荐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"dc990fb2ed9d4c479090cd0bfa772054",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"61f502c91582407f98946a8bcad5278c",
                  "label":"pm hd",
                  "parentDynamicPanel":"01bb3472ce954039b8dd5692fe77aea5",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a447cae2f20b431b9086116d55c7c1b2",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"c45411880e4348b793b0d7415bf1b7af",
                          "label":"",
                          "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":-60},
                            "size":{
                              "width":640,
                              "height":2000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"69ba3b1b2308412d83064b166ec6af8e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":-60},
                                "size":{
                                  "width":640,
                                  "height":2000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/批量操作/u2.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"4b78ee2757304ed0aa95c37ebe3719e3",
                      "label":"状态2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ed9ab43ec53c4ae9847c2671cb3b94a9",
                          "label":"",
                          "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":-60},
                            "size":{
                              "width":640,
                              "height":2000}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1323441b66bb4f55b59625c24c1e7044",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":-60},
                                "size":{
                                  "width":640,
                                  "height":2000}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/批量操作/u4.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"26b76eabb88a4da3bffac95ec8b81ec4",
                      "label":"状态3",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"cf9ad0ff81964ef1a70c2d8c818c5576",
                          "label":"",
                          "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":640,
                              "height":1013}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a01733f0b1ef4baa9da327b11494c900",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":640,
                                  "height":1013}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/批量操作/u6.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"56161685c5aa417697edac5ddaf1022e",
                      "label":"状态4",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"b7f030edfd1e4c8cba0d689f1bc2e020",
                          "label":"",
                          "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":640,
                              "height":897}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"70b779ef1a984f9a90fdd56396f4edc8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"61f502c91582407f98946a8bcad5278c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":640,
                                  "height":897}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/批量操作/u8.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"67e5e818a18646ed985596cac13b50b0",
                  "label":"low",
                  "parentDynamicPanel":"01bb3472ce954039b8dd5692fe77aea5",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":175,
                      "y":1076},
                    "size":{
                      "width":290,
                      "height":50}},
                  "adaptiveStyles":{
}},
{
                  "id":"300406c57d6a4c9daff9f7c3cf90ed0e",
                  "label":"tpo",
                  "parentDynamicPanel":"01bb3472ce954039b8dd5692fe77aea5",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":0},
                    "size":{
                      "width":220,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a56b7864a2a24377906f37f0c1cce858",
          "label":"bd",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"478d995a02524fb7945cd50c2a760237",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3e5b53cf5c0d4ec09724f0bf05e2dab7",
                  "label":"",
                  "parentDynamicPanel":"a56b7864a2a24377906f37f0c1cce858",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbc11c6908f446d79e6bfb60f3124be6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a56b7864a2a24377906f37f0c1cce858",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/批量操作/u13.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2be33297da914cc0bc9d4da3512e44ac",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fcf351a4510c4b9d92daa908aa7243f9",
                  "label":"",
                  "parentDynamicPanel":"a56b7864a2a24377906f37f0c1cce858",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"424db4df6fc240fe8b9bda7c2a9164a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a56b7864a2a24377906f37f0c1cce858",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/批量操作/u15.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"ed3a9a95ad6e45539a7c0c7e5b1dec8f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":15},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 pm hd 到 状态2,<br>bd 到 状态2",
                      "panelsToStates":[{
                          "panelPath":["61f502c91582407f98946a8bcad5278c"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["a56b7864a2a24377906f37f0c1cce858"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"53f6e9589ee641a19cdd96b108dd9a1c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":15},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 pm hd 到 状态1,<br>bd 到 状态1",
                      "panelsToStates":[{
                          "panelPath":["61f502c91582407f98946a8bcad5278c"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["a56b7864a2a24377906f37f0c1cce858"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"6cbd938c4f5a4c6e90773c77ef8da8d6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":80},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 pm hd 到 状态3",
                      "panelsToStates":[{
                          "panelPath":["61f502c91582407f98946a8bcad5278c"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"b402b440779f4b40be7e9395df74c4f9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":150},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 pm hd 到 状态4",
                      "panelsToStates":[{
                          "panelPath":["61f502c91582407f98946a8bcad5278c"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"6872669b8d5c4336874d6a221647c6b8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 本地歌曲",
                      "target":{
                        "targetType":"page",
                        "url":"本地歌曲.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "01bb3472ce954039b8dd5692fe77aea5":{
      "scriptId":"u0"},
    "61f502c91582407f98946a8bcad5278c":{
      "scriptId":"u1"},
    "c45411880e4348b793b0d7415bf1b7af":{
      "scriptId":"u2"},
    "69ba3b1b2308412d83064b166ec6af8e":{
      "scriptId":"u3"},
    "ed9ab43ec53c4ae9847c2671cb3b94a9":{
      "scriptId":"u4"},
    "1323441b66bb4f55b59625c24c1e7044":{
      "scriptId":"u5"},
    "cf9ad0ff81964ef1a70c2d8c818c5576":{
      "scriptId":"u6"},
    "a01733f0b1ef4baa9da327b11494c900":{
      "scriptId":"u7"},
    "b7f030edfd1e4c8cba0d689f1bc2e020":{
      "scriptId":"u8"},
    "70b779ef1a984f9a90fdd56396f4edc8":{
      "scriptId":"u9"},
    "67e5e818a18646ed985596cac13b50b0":{
      "scriptId":"u10"},
    "300406c57d6a4c9daff9f7c3cf90ed0e":{
      "scriptId":"u11"},
    "a56b7864a2a24377906f37f0c1cce858":{
      "scriptId":"u12"},
    "3e5b53cf5c0d4ec09724f0bf05e2dab7":{
      "scriptId":"u13"},
    "dbc11c6908f446d79e6bfb60f3124be6":{
      "scriptId":"u14"},
    "fcf351a4510c4b9d92daa908aa7243f9":{
      "scriptId":"u15"},
    "424db4df6fc240fe8b9bda7c2a9164a4":{
      "scriptId":"u16"},
    "ed3a9a95ad6e45539a7c0c7e5b1dec8f":{
      "scriptId":"u17"},
    "53f6e9589ee641a19cdd96b108dd9a1c":{
      "scriptId":"u18"},
    "6cbd938c4f5a4c6e90773c77ef8da8d6":{
      "scriptId":"u19"},
    "b402b440779f4b40be7e9395df74c4f9":{
      "scriptId":"u20"},
    "6872669b8d5c4336874d6a221647c6b8":{
      "scriptId":"u21"}}});