$axure.loadCurrentPage({
  "url":"引导页.html",
  "generationDate":new Date(1428321654043.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66b19b594caa412c8fcc0074fa104865",
    "type":"Axure:Page",
    "name":"引导页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f5dacc4bae5e4e76a48ef27856f66c54",
          "label":"yd",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 yd 到 Next 向左滑动 out 500ms 向左滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["f5dacc4bae5e4e76a48ef27856f66c54"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 yd 到 Previous 向右滑动 out 500ms 向右滑动 in 500ms",
                      "panelsToStates":[{
                          "panelPath":["f5dacc4bae5e4e76a48ef27856f66c54"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideRight",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9b89088a9f684a18ba366a15fdc9ba61",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cd57646993184fecb64166de6da0693f",
                  "label":"",
                  "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":1136}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce9c5aa54da547438919b4755bcf804e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":1136}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/引导页/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"875d8bf4788c4034af1afc42f2a2b79e",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0fdc2f4cfd49465598f83a389d75a080",
                  "label":"",
                  "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":1136}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbe6a6c65c2f4750a2ad5f2fa383081a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":1136}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/引导页/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2de3e070dff240d4bed6d80ff5e9e967",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ed89495ed933447186589a5767dd87bc",
                  "label":"",
                  "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":1136}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25df2bb9778043619bd80ba00ef4cd1c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":1136}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/引导页/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"b5dafee3cb414b0bbdde82ed610ec21f",
              "label":"状态4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"461c41c1adb3469bbd5eea508d62cb4b",
                  "label":"",
                  "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":1136}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"945d05924a33411c929f171b1bd6be42",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":1136}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/引导页/u7.png"}},
{
                  "id":"3838909e029147c387dd3e8337a5b32c",
                  "label":"",
                  "parentDynamicPanel":"f5dacc4bae5e4e76a48ef27856f66c54",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":470,
                      "y":480},
                    "size":{
                      "width":160,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "f5dacc4bae5e4e76a48ef27856f66c54":{
      "scriptId":"u0"},
    "cd57646993184fecb64166de6da0693f":{
      "scriptId":"u1"},
    "ce9c5aa54da547438919b4755bcf804e":{
      "scriptId":"u2"},
    "0fdc2f4cfd49465598f83a389d75a080":{
      "scriptId":"u3"},
    "fbe6a6c65c2f4750a2ad5f2fa383081a":{
      "scriptId":"u4"},
    "ed89495ed933447186589a5767dd87bc":{
      "scriptId":"u5"},
    "25df2bb9778043619bd80ba00ef4cd1c":{
      "scriptId":"u6"},
    "461c41c1adb3469bbd5eea508d62cb4b":{
      "scriptId":"u7"},
    "945d05924a33411c929f171b1bd6be42":{
      "scriptId":"u8"},
    "3838909e029147c387dd3e8337a5b32c":{
      "scriptId":"u9"}}});