$axure.loadCurrentPage({
  "url":"本地歌曲.html",
  "generationDate":new Date(1428321654151.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0a22ee72765c4ea58155dca516e1be84",
    "type":"Axure:Page",
    "name":"本地歌曲",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f8ad88c8cb640b08ab4c18d763ded84",
          "label":"pm",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":174},
            "size":{
              "width":640,
              "height":910}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1<br> (If area of pm hd 接触到 area of low 和 area of pm hd 接触到 area of tpo)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"IsOver",
                      "arguments":[{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["30addbf9759c48ee84bdf1f6a62cd259"]}]},
{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["8f3b58dab6e9439db94418d8acd3a9ca"]}]}]},
                    "rightExpr":{
                      "exprType":"fcall",
                      "functionName":"IsOver",
                      "arguments":[{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["30addbf9759c48ee84bdf1f6a62cd259"]}]},
{
                          "exprType":"fcall",
                          "functionName":"GetWidgetRectangles",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["492ff934990a4117ba7c9e88d2d2411d"]}]}]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 沿 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["30addbf9759c48ee84bdf1f6a62cd259"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"用例 2<br> (Else If area of pm hd 未接触 area of tpo)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["30addbf9759c48ee84bdf1f6a62cd259"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["492ff934990a4117ba7c9e88d2d2411d"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 到 (0,0) 弹跳 500ms",
                      "objectsToMoves":[{
                          "objectPath":["30addbf9759c48ee84bdf1f6a62cd259"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"easeOutBounce",
                              "duration":500}}}]}]},
{
                  "description":"用例 3<br> (Else If area of pm hd 未接触 area of low)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["30addbf9759c48ee84bdf1f6a62cd259"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["8f3b58dab6e9439db94418d8acd3a9ca"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 到 (0,-863) 弹跳 500ms",
                      "objectsToMoves":[{
                          "objectPath":["30addbf9759c48ee84bdf1f6a62cd259"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-863",
                              "stos":[]},
                            "options":{
                              "easing":"easeOutBounce",
                              "duration":500}}}]}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 推荐",
                      "target":{
                        "targetType":"page",
                        "url":"推荐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"396b6ee30f2b4f38ae81a6e06163ee13",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"30addbf9759c48ee84bdf1f6a62cd259",
                  "label":"pm hd",
                  "parentDynamicPanel":"7f8ad88c8cb640b08ab4c18d763ded84",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"37a9d78aad6d4e37819aad4a89475798",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"603de47c6fbc4d79bf120d5577451392",
                          "label":"",
                          "parentDynamicPanel":"30addbf9759c48ee84bdf1f6a62cd259",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":640,
                              "height":1738}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1d4dd1c2b38644278f223c43d10c7630",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"30addbf9759c48ee84bdf1f6a62cd259",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":640,
                                  "height":1738}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/本地歌曲/u2.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"8f3b58dab6e9439db94418d8acd3a9ca",
                  "label":"low",
                  "parentDynamicPanel":"7f8ad88c8cb640b08ab4c18d763ded84",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":175,
                      "y":909},
                    "size":{
                      "width":290,
                      "height":50}},
                  "adaptiveStyles":{
}},
{
                  "id":"492ff934990a4117ba7c9e88d2d2411d",
                  "label":"tpo",
                  "parentDynamicPanel":"7f8ad88c8cb640b08ab4c18d763ded84",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":0},
                    "size":{
                      "width":220,
                      "height":50}},
                  "adaptiveStyles":{
}},
{
                  "id":"6efcfdf8ac384eec90cf98738474abc8",
                  "label":"",
                  "parentDynamicPanel":"7f8ad88c8cb640b08ab4c18d763ded84",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-154},
                    "size":{
                      "width":640,
                      "height":2000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ea4c9aee7c843859b2ac0b8c9235d4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f8ad88c8cb640b08ab4c18d763ded84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-154},
                        "size":{
                          "width":640,
                          "height":2000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/本地歌曲/u6.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"cd916e74d0464983bcac9dc5cfc029fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d567c322beea4dc4b7aba5ede0ddeb28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/本地歌曲/u8.png"}},
{
          "id":"f3d8c8ddde8c4b768761d704790bc034",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":70},
            "size":{
              "width":640,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38fca7adad9349d38930b3cbd7f4fffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":70},
                "size":{
                  "width":640,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/本地歌曲/u10.png"}},
{
          "id":"b1de89dd49ff4cd4afb04eb4c4d8a179",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1084},
            "size":{
              "width":640,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084e2b032fb845a09e36b8cc1cd3ad69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1084},
                "size":{
                  "width":640,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/本地歌曲/u12.png"}},
{
          "id":"a89a5ed281aa4804aaf65f5e6856a69b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":220},
            "size":{
              "width":50,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 pm hd 到 (0,0) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["30addbf9759c48ee84bdf1f6a62cd259"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "tabbable":true},
{
          "id":"09b1e05d3c4541d29778d0c1a3e2ab80",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":135},
            "size":{
              "width":170,
              "height":34}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 批量操作",
                      "target":{
                        "targetType":"page",
                        "url":"批量操作.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"488333ee069e48eda985e3884f454a43",
          "label":"xx",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":320,
              "y":152},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"72bc64fe4a174434956c9bbc6e005f22",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e4883d219dc84df08197d183ab93c173",
                  "label":"",
                  "parentDynamicPanel":"488333ee069e48eda985e3884f454a43",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":600,
                      "height":400}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38ac5d0b163547a7b3d6e7f9f502c78c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"488333ee069e48eda985e3884f454a43",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":600,
                          "height":400}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/本地歌曲/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"6f0889379faa427eb53853f6de862a8a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":135},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 xx",
                      "objectsToFades":[{
                          "objectPath":["488333ee069e48eda985e3884f454a43"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"276f7c55cec543dcbaead3a332397fc1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 xx",
                      "objectsToFades":[{
                          "objectPath":["488333ee069e48eda985e3884f454a43"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"cac76e0ed38c45448b7c0ef67397da61",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":179},
            "size":{
              "width":160,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 扫描",
                      "target":{
                        "targetType":"page",
                        "url":"扫描.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2f18a965548c41149bb7b870bbd68c46",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":15},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a7f7622231514151a2aeadf1804be384",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":20},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"414c5f4a1af94fa2a26c2ed277eb9dd1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":20},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "7f8ad88c8cb640b08ab4c18d763ded84":{
      "scriptId":"u0"},
    "30addbf9759c48ee84bdf1f6a62cd259":{
      "scriptId":"u1"},
    "603de47c6fbc4d79bf120d5577451392":{
      "scriptId":"u2"},
    "1d4dd1c2b38644278f223c43d10c7630":{
      "scriptId":"u3"},
    "8f3b58dab6e9439db94418d8acd3a9ca":{
      "scriptId":"u4"},
    "492ff934990a4117ba7c9e88d2d2411d":{
      "scriptId":"u5"},
    "6efcfdf8ac384eec90cf98738474abc8":{
      "scriptId":"u6"},
    "9ea4c9aee7c843859b2ac0b8c9235d4e":{
      "scriptId":"u7"},
    "cd916e74d0464983bcac9dc5cfc029fe":{
      "scriptId":"u8"},
    "d567c322beea4dc4b7aba5ede0ddeb28":{
      "scriptId":"u9"},
    "f3d8c8ddde8c4b768761d704790bc034":{
      "scriptId":"u10"},
    "38fca7adad9349d38930b3cbd7f4fffd":{
      "scriptId":"u11"},
    "b1de89dd49ff4cd4afb04eb4c4d8a179":{
      "scriptId":"u12"},
    "084e2b032fb845a09e36b8cc1cd3ad69":{
      "scriptId":"u13"},
    "a89a5ed281aa4804aaf65f5e6856a69b":{
      "scriptId":"u14"},
    "09b1e05d3c4541d29778d0c1a3e2ab80":{
      "scriptId":"u15"},
    "488333ee069e48eda985e3884f454a43":{
      "scriptId":"u16"},
    "e4883d219dc84df08197d183ab93c173":{
      "scriptId":"u17"},
    "38ac5d0b163547a7b3d6e7f9f502c78c":{
      "scriptId":"u18"},
    "6f0889379faa427eb53853f6de862a8a":{
      "scriptId":"u19"},
    "276f7c55cec543dcbaead3a332397fc1":{
      "scriptId":"u20"},
    "cac76e0ed38c45448b7c0ef67397da61":{
      "scriptId":"u21"},
    "2f18a965548c41149bb7b870bbd68c46":{
      "scriptId":"u22"},
    "a7f7622231514151a2aeadf1804be384":{
      "scriptId":"u23"},
    "414c5f4a1af94fa2a26c2ed277eb9dd1":{
      "scriptId":"u24"}}});