$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1428321654684.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0bf1a8a39c6c4b41adadf468c00baebc",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55d64cdd49d343f892ca60017f1092a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8467a35f4487481b936d9c82949c514a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"c25edd05c4aa4ce59aaf8a4c1fa74355",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":140,
              "y":260},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"65aa1cadd95d49008d1a21295e8a28a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":140,
              "y":400},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"df160517b7cc416db41d42882b340ad0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ae460110e42d41d887238dfcf7c1e597",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":526},
            "size":{
              "width":631,
              "height":94}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b312359cb4804b5586f554824d93c9cd",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"a02d66202a7d4a32be7ce530de7185b6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"eef33cd1fd764a249ec82e71e106b88f",
                  "label":"",
                  "parentDynamicPanel":"ae460110e42d41d887238dfcf7c1e597",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":625,
                      "height":96}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6cd3551eb8f34b93a0aa5cec2664d02d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ae460110e42d41d887238dfcf7c1e597",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":625,
                          "height":96}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 搜索",
                              "target":{
                                "targetType":"page",
                                "url":"搜索.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录/u6.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"df5a72a260fe4ed0b89d31cd6236f2ea",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":466},
            "size":{
              "width":270,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) 到 状态1",
                      "panelsToStates":[{
                          "panelPath":["ae460110e42d41d887238dfcf7c1e597"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "55d64cdd49d343f892ca60017f1092a7":{
      "scriptId":"u0"},
    "8467a35f4487481b936d9c82949c514a":{
      "scriptId":"u1"},
    "c25edd05c4aa4ce59aaf8a4c1fa74355":{
      "scriptId":"u2"},
    "65aa1cadd95d49008d1a21295e8a28a0":{
      "scriptId":"u3"},
    "df160517b7cc416db41d42882b340ad0":{
      "scriptId":"u4"},
    "ae460110e42d41d887238dfcf7c1e597":{
      "scriptId":"u5"},
    "eef33cd1fd764a249ec82e71e106b88f":{
      "scriptId":"u6"},
    "6cd3551eb8f34b93a0aa5cec2664d02d":{
      "scriptId":"u7"},
    "df5a72a260fe4ed0b89d31cd6236f2ea":{
      "scriptId":"u8"}}});